### ISSUE TITLE
Competition Bundle: Basic Functionality

### ISSUE THREAD

**Issue by Tthomas63** [codalab/competitions-v2#101]
- A user should be able to submit a competition bundle respecting the new YAML schema generated in 2018 and the competition should be created successfully.:
  - [x] Define task/function to un-pack and create a competition from a zip bundle according to our YAML specs.

- A user should be able to edit bundle from the editor.
  - [ ] ~Have an edit page for competitions (With a form)~ Holding off on this until we have confirmation of how Tasks should be working

- [x] ~Write Automated tests for frontend using Selenium where applicable~

- [x] Selenium test for uploading a competition bundle -- may need to make Celery run in "eager" mode, so tasks are executed immediately and not by workers

- [x] Migrate to new schema (Remove ingestion and scoring module)

*Note: May need to break into smaller issues*

**Comment by jimmykodes** [comment]
- [ ] decide on UI and design yaml from there

**Comment by jimmykodes** [comment]
@ckcollab where do we stand on this? we merged the PR, can we move this to 'Done' or is there more to do still?
