### ISSUE TITLE
Advanced Functionality: Uploads/Tasks&Solutions

### ISSUE THREAD

**Issue by Tthomas63** [codalab/competitions-v2#103]
Refine and polish tasks and solutions behavior

- [x] ~“My datasets” should be upgraded to support the new task/solution setting.~ We have specific pages for managing tasks + solutions now, they are a special-ish case

- [x] Support using datasets/code separately from the bundle and tie them in with keys

- [x] Ability to upload > 10gb zip files -- competition upload, for example (or submission upload if easier); can use `mkfile -n 10g temp.zip`

**Comment by jimmykodes** [comment]
Eric was able to upload 10gb file on remote server. Issues with loading this file locally on MacOS _may_ be due to docker worker configurations, regardless, it works on an actual server.
