### ISSUE TITLE
UI and Chahub Changes

### ISSUE THREAD

**Issue by Tthomas63** [codalab/competitions-v2#104]
- [ ] V2 Integrate with ChaHub (push competitions/datasets/etc.)
  - [ ] Set-up v2 to push data for:
    - [ ] Datasets
    - [ ] Competitions
    - [ ] Submissions

- [ ] Incorporate all the AutoDL UI changes into V2.

**Comment by jimmykodes** [comment]
closing this as some of this has been done and is being tracked elsewhere
