### ISSUE TITLE
Compute worker actually saves to stdout/stderr files appropriately

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#126]
We return data via sockets already, but the data isn't saved ("persisted") after the run is finished. We receive SAS keys at the beginning of a run for storing `stdout` and `stderr` -- should use 'em.

Maybe the best route is to augment `async def _run_docker_cmd(self, docker_cmd):` to upload these files when completed?

```python
            stdout, stderr = await proc.communicate()

            logger.info(f'[exited with {proc.returncode}]')
            if stdout:
                logger.info(f'[stdout]\n{stdout.decode()}')
            if stderr:
                logger.info(f'[stderr]\n{stderr.decode()}')
```

It should be set here, examine what the logger is outputting

**Comment by jimmykodes** [comment]
address in submission manager
