### ISSUE TITLE
Meet with Isabelle re: Task/Solutions (ingestion module, scoring module)

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#130]
Specifically, how do we want to manage modules and such?

We will need 3 new management pages/screens:
- Task management
- Ingestion module management
- Scoring module management

It may make more sense to just to Task management and get rid of the idea of modules all together?

**Comment by jimmykodes** [comment]
tasks:
  - index: 0
    name: "Test task"
    description: "A test task"
    ingestion_module:
      name: "Test ingestion module"
      description: "A test ingestion module"
      ingestion_program: "ingestion_program.zip"
      input_data: "input_data.zip"
      only_during_scoring: True
    scoring_module:
      name: "Test solution"
      description: "A test solution"
      scoring_program: "scoring_program.zip"
      reference_data: "reference_data.zip"
