### ISSUE TITLE
Competition participant features

### ISSUE THREAD

**Issue by jimmykodes** [codalab/competitions-v2#134]
- [x] Competitions should have a field “registration required”
- [x] If registration is required, competitions should have a "terms" attached?
- [x] Competitions sometimes need a “Terms” agreement before entering them
This may involve a special named markdown file in the bundle -- maybe we can just allow marking 1 page as “terms”?
    - [x] Competitions sometimes require the participant to be “accepted” -- they can also be “denied”
- [x] Table for managing participants
    - [x] Sortable, filterable, etc. where applicable
    - [x] Action buttons: accept, revoke, ~message (maybe?)
    - [x] On this page you should be able to send a message to all participants

**Comment by jimmykodes** [comment]
![image](https://user-images.githubusercontent.com/37089863/52247744-ecd7fd80-289f-11e9-904b-be478c298997.png)

**Comment by ckcollab** [comment]
![image](https://user-images.githubusercontent.com/2185159/52247808-358fb680-28a0-11e9-955c-e92ef8bbedfe.png)

**Comment by jimmykodes** [comment]
completed
