### ISSUE TITLE
Submission manager

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#136]
- [ ] Finalize submission Manager

Clean up the division of work between the ingestion program and the
scoring program, such that they can be run in parallel in tight compartments, interacting via storage only. Check security of data: only the scoring program should have access to truth values.

Support a variety of use cases with result or code submission and the possibility of using a scoring program interacting with the outside world (e.g. scores provided by humans or by an external
web service).

You can see how the ingestion program and such work currently on the old compute worker, here:
https://github.com/codalab/competitions-v1-compute-worker/blob/feature/legacy-azure-version-fix/worker.py#L511

Example scenario where a user makes a CODE submission to a phase with an INGESTION PROGRAM..

Compute worker:
1. Receives task args
1. Check whether `is_scoring` -- otherwise we're doing a prediction 
1. If predicting AND we have task args with an ingestion AND our submission is code:
    - we need to run something along side the regular submission
1. If submission is results, not code, just zip it up as a result and submit that (can explain more)
1. Run submission AND ingestion at the same time, ingestion should receive the `hidden_directory` of data to work with.

**Comment by jimmykodes** [comment]
Let's just worry about ingestion program during prediction step right now

- [ ] Student submission stdout/stderr is saved after run
- [ ] Ingestion program stdout/stderr is saved after run
- [ ] Ingestion program is passed a volume containing a submission

**Comment by jimmykodes** [comment]
## Admin Page
- create admin tab on competition menu next to leaderboard (viewable if you are comp creator or collaborator
- Admin page should have tabs for various things that will require 'administrating'
    - the only tab this issue cares about is `Submissions`
- Submissions tab should have a table with all the submissions for _all_ the phases of the competition
    - Above the headers of the table, there should be a search field where you can search submissions by name (and maybe by author)
    - There should also be a dropdown menu that lets you filter by phase
    - Maybe another dropdown menu to filter by status?

## Maybe Things?
- Add functionality to change scores?
- Download submissions as CSV?
- Rerun all submissions per phase?

## Add buttons to submission row?
- Delete submission
- Rerun submission
- Cancel submission
 
## Create modal for submission w/
- Downloads tab
    - Download Submission
    - Download output from prediction step
    - Download output from scoring step
    - Download private output from scoring step
- View Logs
    - Predict stdout
    - Predict stderr
    - Predict ingestion_stdout
    - Predict ingestion_stderr
    - Scoring stdout
    - Scoring stderr
    - Scoring ingestion_stdout
    - Scoring ingestion_stderr

**Comment by ckcollab** [comment]
TODO: Make an issue filled with checkboxes for "acceptance criteria" determining this task is done
