### ISSUE TITLE
Worker issue for V2 large uploads

### ISSUE THREAD

**Issue by jimmykodes** [codalab/competitions-v2#137]
Possibly the 10gb issue is related to local uvicorn.workers.UvicornWorker timing out.

https://github.com/benoitc/gunicorn/issues/1440

**Comment by ckcollab** [comment]
do we want to close this? seems specific to mac osx docker, so not a huge deal since it goes through on linux fine?

**Comment by jimmykodes** [comment]
Was just about to close the issue actually 👍🏻
