### ISSUE TITLE
Selenium Tests

### ISSUE THREAD

**Issue by Tthomas63** [codalab/competitions-v2#138]
## Selenium Test Bank:
___
- [x] Login
- [x] Making a submission (but not running on compute worker)
- [x] uploading v1.5 style competition (via bundle converter)
- [x] uploading task style competition
- [x] get selenium tests running in circleCI
- Running a submission on compute worker
    - [x] making submission to v1.5 competition
    - [x] making submission to task/solution competition
___
- [ ] Creating competition through UI (not bundle upload)
- [ ] Joining competition as participant

**Comment by jimmykodes** [comment]
Use this issue as a bank of selenium tests that need to be written and break out from it a few tests at a time per sprint.
