### ISSUE TITLE
Chahub Auth:

### ISSUE THREAD

**Issue by Tthomas63** [codalab/competitions-v2#155]
Re-visit + Re-implement:

- Check-out old code/attempts
- Make style more like Chagrade's Chahub Auth

**Comment by Tthomas63** [comment]
Ref: https://github.com/codalab/chahub/issues/53

Local Chahub Auth Problems:
 - [ ] Multiple accounts (solution: Merge account manager)
 - [ ] Recover old/deleted competitions:
     - Any solution would go against GPDR. I think we should just warn them, and then destroy the files.
     - Also have deleting files from storage on model delete working for another project
     - Solution would be set all sensitive user info to null/anonymous-{id} or something similar, but keep references to the old values somewhere to reset? Or just allow the user themselves to change it.
 - [ ] Chahub Sign-In:
    - We could try and package our adapter into a Django app you include? This could allow almost any site to implement this similar to what we're already doing.
- [ ] Associate Users to submissions on chahub:
    - When signing in through Chahub we could store the Chahub User ID on the user under a field like `chahub_user_id`.
    - Then when we receive submissions we could also send this info along (Not required) and if sent it would be associated with the existing user on Chahub (If found). 
    - We need to be concerned with security concerns with something like that, so we might be able to implement an Oauth2 adapter on DRF (If not already) then use our access token from our Chahub association to make a request to the API authorized under that user?
- [x] Race condition with submission on producer vs creating user on Chahub(???)
  -  All accounts should be created through Chahub, redirecting back to the producer so this should not happen. Chahub is the authoritative. Unless we have some way of securely transmitting the sensitive data able to create a user to Chahub, this does not seem possible.

**Comment by Tthomas63** [comment]
### Checklist:

- [ ] Hand tests passing
- [ ] Automated tests passing
- [ ] Code Reviewed by Tyler
- [ ] Code peer reviewed
- [ ] Code ready to merge

## Acceptance Criteria:
### Chahub Side:
#### General
 - [ ] Can begin Oauth with Chahub, sign-up instead of login, and be redirected back properly to continue auth
   - Setting for allowed domains, besides producer domains
 - [ ] Can automatically create new Oauth applications for producers, or those in allowed domains
 - [ ] Can return basic user information to v2/v1.5
 - [ ] Can return `github_info` and other 3rd party info to producer/codalab instance
 - [ ] Can associate competitions, submissions etc back to a user if sent the proper information.
 - [ ] Authorization template/message is more clear/less wordy
#### Merging accounts
 - [ ] Can merge duplicate accounts
   * account management page/form
 - [ ] Can delete/nullify account
   * Should this be recoverable(?) GPDR does not really allow for that.
   * If it shouldn't be recoverable, have deleting of file storage objects when associated models get deleted set-up, and then simply delete the user with the other information cascading.
   * If it should be recoverable, set all sensitive information to null/blank/anonymous

### Producer (v1.8/v2) Side:
- [ ] Can associate a Chahub account with an existing account
  * If emails differ, do we update, or ask?
- [ ] Can create a new account from your Chahub user
- [ ] Can utilize github info if authed with Github on Chahub.
  * USE CASE: If Authed on Chagrade through Chahub, and there is github_info associated with the Chahub user, we should be able to populate a list of repositories, branches, and commits for the user on Chagrade (For making submissions, etc)
- [ ] Can merge local duplicate accounts
  * If different Chahub users are associated for the users, prevent(?) or allow multiple
  * If the same, or only one Chahub user is associated for the users merge
- [ ] Can associate profiles, competitions, datasets, etc that are being sent to Chahub with the associated user (If existing).

**Comment by Tthomas63** [comment]
### Profiles To Do:
- [ ] User/Profile tile changes
- [ ] Testing/Verifying Search changes
- [ ] Multiple URLs for profiles view
  - [ ] One for specific remote_id + producer combinations
  - [ ] One for multiple profile/user combinations by username
- [ ] Implement two different display styles:
  - [ ] Combined mode for profiles/users (Combine all profiles on a user, or all profiles with a given username)
- [ ] Linking to profile page from search (Links to specific (producer + remoted_id) detail apge)

### Auth To Do:
- [ ] Implement the ability to re-direct from the Chahub Sign-up page/process
  - [ ] Allow a next parameter to point to a URL to redirect to, whitelisting domains based off whether they're a producer, or in a whitelist in settings.
  - [ ] Any sign-up links from v2/chagrade/etc should include that next_param as the `social/login/chahub` url for that domain.
- [ ] Account management page/views/templates
  - [ ] A way to merge two local accounts with different emails
  - [ ] A way to merge two Chahub accounts with different emails

See https://github.com/codalab/competitions-v2/issues/155 for addressing specs.

**Comment by jimmykodes** [comment]
completed and merged into develop
