### ISSUE TITLE
Acceptance criteria for sub manager

### ISSUE THREAD

**Issue by jimmykodes** [codalab/competitions-v2#161]
Connect #136
# Acceptance Criteria
- [x] @ckcollab -> ingestion program has a hidden_directory
___
## General
- [x] stdout/stderr saved
  - [x] storage location is private bucket
  - [x] prediction step stdout/stderr and ingestion stdout/stderr saved
  - [x] scoring step stdout/stderr and ingestion stdout/stderr saved
## Submission adim tab
- [x] admin tab only viewable if you are 
  - [x] comp admin
  - [x] collaborator 
  - [x] superuser
- [x] admin tab has submission management tab
- [x] submission table defaults to whole competition
- [x] table should be filterable
  - [x] by phase
  - [x] by submission status
- [x] table should be searchable
  - [x] by file name
  - [x] by 'owner' (person who made the submission)
- [x] the data reflected in the table should be downloadable by CSV w/ a button
- [x] the submission for a specified phase should be able to be re-run in bulk
  - [x] this should return how many submission have been re-run
- [x] The following functionality should be executable per single submission:
  - [x] Rerun submission
  - [x] Delete submission
  - [x] cancel submission
    - [x] Should only be able to cancel a submission that is running (i.e. status is NOT `finished` or `failed`)
- [x] the `owner`, `phase`, and `actions` columns should only be viewable in the table in the admin tab
### General modal
- [x] Able to download submission zip
- [x] able to download output from prediction step
- [x] placeholder to eventually download output from scoring step (not currently available)
- [x] placeholder to eventually download private output from scoring step (not currently available)
- [x] can view prediction step stdout/stderr and ingestion stdout/stderr
- [x] can view scoring step stdout/stderr and ingestion stdout/stderr
### Admin specific modal
- [x] modal admin tab only viewable if submission row clicked from table in submission manager admin tab
- [x] can view and manually change scores
  - [x] cannot change computed column scores
  - [x] this works with leaderboard w/ multiple columns
  - [x] this works with competition w/ multiple leaderboards

**Comment by jimmykodes** [comment]
@ckcollab I've bulked out the acceptance criteria for the submission manager, but I have a section at the top of things from the SoW that don't really make sense to me, (still... even though I feel like I should by now...) so I'll need your help creating the acceptance criteria for those details.

**Comment by ckcollab** [comment]
I think hidden dir handling is fine for now, let's go forward with this
