### ISSUE TITLE
Review Submission Manager

### ISSUE THREAD

**Issue by jimmykodes** [codalab/competitions-v2#162]
## Checklist before asking for review
- [x] Added some tests covering new behavior, or if a bug, potentially add a failing test proving this change fixes the problem
- [x] Tests pass (except for the one weird one I commented out. Hoping the reason may become obvious during review?)
- [ ] I have reviewed my own code and pulled comments, cruft, etc.
- [x] I am proud of what I wrote
## Checklist for reviewer
- [x] Acceptance Criteria met: #161 (just waiting on check for hidden dir stuff from Eric)
- [ ] I read through this code and find it to be kick ass, I accept some responsibility for it failing (if it does!)

**Comment by ckcollab** [comment]
I think this checklist should go in the PR so we have 1 issue and 1 pr?

**Comment by jimmykodes** [comment]
tracked elsewhere
