### ISSUE TITLE
YAML validator acceptance criteria

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#172]
- [x] ~Repo for yaml validator~ https://github.com/codalab/codalab-bundle-validator
- [ ] Validator accepts new task + solution style YAML
- [ ] Can pip install the validator
- [ ] Can read nice descriptions about validator on Wiki
- [ ] Takes in 2 zip files (or folders?) as arguments
- [ ] Prints differences in YAML files
- [ ] Prints differences in file/folder structure
- [ ] Prints differences in MD5 hashes ?

**Comment by jimmykodes** [comment]
Issue moved to Yaml Validator Repo
