### ISSUE TITLE
Chahub Auth acceptance criteria

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#179]
- [ ] v1.5 and v2 ability to "Connect with Chahub"
- [ ] ??? v1.5 and v2 "Sign in with Github" redirects to Chahub ???
- [ ] Ability to "Connect with Github" from Chahub
- [ ] On chahub have some kind of feature where if 2 emails authorize merging, both accounts are merged together but each email is saved to point to that one main account
- [ ] v1.5 and v2 send as much information as possible for profiles to Chahub (submissions, competitions, etc.)
- [ ] Uncheck these when done and re-assign to Isabelle, label for review

**Comment by jimmykodes** [comment]
This work has been completed
