### ISSUE TITLE
Isabelle Review Comp Editor

### ISSUE THREAD

**Issue by jimmykodes** [codalab/competitions-v2#184]
Review here:
http://134.158.74.47/
login
admin:admin

# Acceptance Criteria
## General
- [x] Save and publish saves comp, publishes comp, takes you to comp detail page
- [x] Save as draft saves comp, does not publish it, keeps you on the edit page
- [x] Discard changes takes you back to competition list page and does not save the comp
- [x] Comp edit form can be reached from:
  - [x] Competition list page via "edit" button on competition row
  - [x] Competition list page via "create" button
  - [x] Admin tab of competition detail page
<hr/>
http://134.158.74.47/competitions/2/
<img width="1047" alt="Screen Shot 2019-05-03 at 3 03 45 PM" src="https://user-images.githubusercontent.com/37089863/57167992-bafa0880-6db4-11e9-9413-b4283b93b483.png">
<hr/>
http://134.158.74.47/competitions/
<img width="1041" alt="Screen Shot 2019-05-03 at 3 07 09 PM" src="https://user-images.githubusercontent.com/37089863/57168106-3491f680-6db5-11e9-9725-7738c006198a.png">
<hr/>
http://134.158.74.47/competitions/edit/2/
<img width="956" alt="Screen Shot 2019-05-03 at 3 10 40 PM" src="https://user-images.githubusercontent.com/37089863/57168222-b124d500-6db5-11e9-8d1c-2b7055659c2a.png">

## Competition Details Tab
- [x] Can change competition title
- [x] Can change competition logo
## Pages Tab
- [x] Can Add pages
- [x] Can edit page titles and content
- [x] Can delete pages
- [ ] Page content for page at index 0 displayed as valid content w/ xss vulnerabilities removed
  - [ ] can write html
## Phases Tab
- [ ] reordering phases changes phase index
#### Phase details tab
- [ ] Change name (required)
- [ ] Change Description (required)
- [ ] Change start (required)
- [ ] Change end
- [ ] Valid when all required fields met
#### Phase Data tab
- [ ] Dataset manager button takes you to dataset management page in new tab
- [ ] Task Manager button takes you to Task management page in new tab
- [ ] Toggle to change between dataset and task/solution style phase. Loads w/ correct value on edit
##### Toggled off (not task/solution)
- [ ] dataset selection form should be present
  - [ ] filled with correct values if editing
##### Toggled `on` (is task/solution)
- [ ] Should not save any values in dataset form fields
- [ ] Task multi-select field present
  - [ ] Preselects correct data on edit
  - [ ] Appropriately searches
  - [ ] Can select and save multiple tasks
  - [ ] On edit, can add tasks to phase that already has tasks
##### Data Tab Validation
- [ ] Data tab should validate properly (i.e. save button enabled)
  - [ ] when task/solution toggle is _off_ and `scoring program` dataset is set
  **or**
  - [ ] when task/solution is _on_ and Tasks field has at least 1 value
## Leaderboard Tab
- [ ] when unsetting a previously set computation field, also unset computation indexes
- [ ] when setting computation field, correctly save computation indexes
- [ ] correctly fill leaderboard column key when editing leaderboard
- [ ] correctly select primary column radio button on edit
- [ ] changing primary index radio actually changes primary index
## Collaborator Tab
- [ ] Selected collaborators listed in table
- [ ] Can remove collabs from table
- [ ] Search for collabs by username as normal user
- [ ] Search for collabs by complete match email address for normal user
- [ ] Search for collabs by email partial match for admin
- [ ] field errors for adding collab who is already added
- [ ] field errors for trying to add yourself as collab
- [ ] field errors for trying to add comp creator as collab

**Comment by madclam** [comment]
UI: 
1) Not sure we want so prominently to advertise on the main page that you can organize competitions. I like the old main page https://competitions.codalab.org/ and the fact to the button to upload competitions is a little hidden.
2) All top menu functionality is presently inactive and everything available admin the admin pull down. What is the plan?

**Comment by madclam** [comment]
PAGES:

The problem is that when pages are created they appear nowhere in the competition.
See other comments in https://github.com/codalab/competitions-v2/issues/150
Not sure how we can view/write HTML.

PHASES:
Re-ordering does not seem to work.
We do not see the phase information in the phases tab: impossible to check edits made.

OTHER FEATURES:
I need to be walked through them, difficult to figure out wha to do.
