### ISSUE TITLE
Isabelle Review Submission Manager

### ISSUE THREAD

**Issue by jimmykodes** [codalab/competitions-v2#185]
Review here:
http://134.158.74.47/
login
admin:admin

## General
- [ ] stdout/stderr saved
  - [ ] storage location is private bucket
  - [ ] prediction step stdout/stderr and ingestion stdout/stderr saved
  - [ ] scoring step stdout/stderr and ingestion stdout/stderr saved

## Submission adim tab
<img width="1065" alt="Screen Shot 2019-05-03 at 2 58 23 PM" src="https://user-images.githubusercontent.com/37089863/57167816-fc3de880-6db3-11e9-88d6-165aa95d150e.png">

- [ ] admin tab only viewable if you are 
  - [ ] comp admin
  - [ ] collaborator 
  - [ ] superuser
- [ ] admin tab has submission management tab
- [ ] submission table defaults to whole competition
- [x] table should be filterable
  - [ ] by phase
  - [x] by submission status
- [x] table should be searchable
  - [ ] by file name
  - [ ] by 'owner' (person who made the submission)
- [x] the data reflected in the table should be downloadable by CSV w/ a button
- [x] the submission for a specified phase should be able to be re-run in bulk
  - [x] this should return how many submission have been re-run
- [ ] The following functionality should be executable per single submission:
  - [x] Rerun submission
  - [x] Delete submission
  - [x] cancel submission
    - [ ] Should only be able to cancel a submission that is running (i.e. status is NOT `finished` or `failed`)
- [x] the `owner`, `phase`, and `actions` columns should only be viewable in the table in the admin tab
## Submission modal

<img width="1103" alt="Screen Shot 2019-05-03 at 2 59 46 PM" src="https://user-images.githubusercontent.com/37089863/57167898-5179fa00-6db4-11e9-8186-79da479692a4.png">
Modal appears
<img width="1201" alt="Screen Shot 2019-05-03 at 3 02 24 PM" src="https://user-images.githubusercontent.com/37089863/57167937-7a9a8a80-6db4-11e9-8de8-213c63043071.png">

### General modal
- [ ] Able to download submission zip
- [ ] able to download output from prediction step
- [ ] placeholder to eventually download output from scoring step (not currently available)
- [ ] placeholder to eventually download private output from scoring step (not currently available)
- [ ] can view prediction step stdout/stderr and ingestion stdout/stderr
- [ ] can view scoring step stdout/stderr and ingestion stdout/stderr
### Admin specific modal
- [ ] modal admin tab only viewable if submission row clicked from table in submission manager admin tab
- [ ] can view and manually change scores
  - [ ] cannot change computed column scores
  - [ ] this works with leaderboard w/ multiple columns
  - [ ] this works with competition w/ multiple leaderboards

**Comment by madclam** [comment]
I have not checked everything, but see my comments in https://github.com/codalab/competitions-v2/issues/150. We should walk through things together.
