### ISSUE TITLE
Handle legacy competition bundle HTML files by converting them to Markdown

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#2]
We're hoping to use Markdown (or RST or whatever, can make sure we can change it later), so be sure to convert the old HTML in legacy bundles to Markdown. I believe HTML is valid in Markdown, but for nice editors we should probably convert it?

https://pandao.github.io/editor.md/examples/full.html

**Comment by jimmykodes** [comment]
html is valid markdown, sooo this is done?
