### ISSUE TITLE
Isabelle Review Chahub Authentication

### ISSUE THREAD

**Issue by Tthomas63** [codalab/competitions-v2#209]
## Auth Through Chahub
- [ ] Sign up on Chahub: http://ec2-54-212-199-121.us-west-2.compute.amazonaws.com/
  - Login -> Sign up
- [ ] Login on v2 through Chahub: https://competitions-v2-staging.herokuapp.com/
  - Login -> `Sign-in` (Below Login with Chahub)

## Sign Up from v2
- Go back to v2 at: https://competitions-v2-staging.herokuapp.com/
- Click the `Sign-up through Chahub` button instead of `Sign in`
- Create a new account through the form
- Unless an error has occurred, it should return you to v2 logged in under the new Chahub account you created.

## Profiles (WiP):
- Visit: http://ec2-54-212-199-121.us-west-2.compute.amazonaws.com/profiles/detail/YOUR_USERNAME

![image](https://user-images.githubusercontent.com/28552312/60299558-d92a4380-98e1-11e9-8ef9-666ab419ac6a.png)

## Profile/User tiles (WiP):
- From the front page, select the filter button next to search, and filter by users
- Search for your username
![image](https://user-images.githubusercontent.com/28552312/60299523-c7e13700-98e1-11e9-8d44-af513e877d9f.png)

**Comment by jimmykodes** [comment]
Sign up with chahub redirects to local host not staging server.

<img width="1698" alt="image" src="https://user-images.githubusercontent.com/37089863/61566940-ac75d180-aa32-11e9-8ce1-6641010ce96f.png">

**Comment by Tthomas63** [comment]
Should be working now, there was an env-var missing on the v2 staging server.

**Comment by jimmykodes** [comment]
There are no error messages for unsuccessful user creation attempts. A bit aggravating to not know why your attempted user creation doesn't submit.

**Comment by jimmykodes** [comment]
Ok, user creation works now, but: super annoying that there are no errors on user creation form when unsuccessful. 
Also, and this may not be strictly related to Auth, but I guess could be: 
![image](https://user-images.githubusercontent.com/37089863/61656033-a3744280-ac74-11e9-8b53-c461ebb56457.png)
The user dropdown for my newly created user has all the django admin options in their dropdown. Not sure if that is something w/ the dropdown or w/ the user creation portion. My new user doesn't have access to the links though, just can see them.

**Comment by jimmykodes** [comment]
The signup button in v2 header does not link to a page w/ signup through chahub available:
![image](https://user-images.githubusercontent.com/37089863/61656998-c1db3d80-ac76-11e9-9b0b-deb2d65cd9f1.png)
The "Sign up with chahub" button on the front page links you to the v2 login page where you then have to click on the "sign up with chahub" button again.
