### ISSUE TITLE
Competition Participant Behaviors

### ISSUE THREAD

**Issue by jimmykodes** [codalab/competitions-v2#211]
For competitions w/out auto approval:
- What should the content of the email that goes to the competition administrators be?
- Who all should receive the email? Just the comp creator? Or all the collaborators as well?
  - Do we also want to include a field in the yaml that allows admins to specify a list of email addresses to notify?
- Do we include a link in the email to the requesting party's chahub profile if it exists? 
- Do we include approve and deny links in the email? or do we just provide a link to the competition detail page for them to go navigate to the participants table and approve or deny there?
- If a participant has been approved and then they have their acceptance revoked by admin, does their status go to `denied`? or should we add a `revoked` status?
  - if a participant has made submissions and then their participation status is revoked, what happens to their submissions? are they deleted? or just excluded from the leaderboard?
- What details should be hidden from a user until they are accepted into a competition? 
  - Hide the ability to make submissions, anything else?

Competitions that don't require approval:
- Are we allowing competitions that have no "terms" ?
- If the competition does not require approval, how do users "join" the competition? By making a submission? or do we still have some variation of the "accepting the terms" page that just says "Register for this competition"?

Connected to #134

**Comment by ckcollab** [comment]
@jimmykodes I believe this can be closed?
