### ISSUE TITLE
Fix solution -> submission pipeline

### ISSUE THREAD

**Issue by jimmykodes** [codalab/competitions-v2#248]
if the contents of the solution dir are:
```
solution/
  └── model.py
```
this will download as `solution.zip` and this will cause issues with the scoring program if it is expecting something like this:

```python
from model import Model
```
so you have to zip the `model.py` file into `model.py.zip` and then you can use the above import statement.
How should we fix this?

**Comment by ckcollab** [comment]
Is this fixed @jimmykodes?
