### ISSUE TITLE
Isabelle review: legacy bundle handling

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#259]
# How to

Go here:
https://codalabcomp-v2-prod.lri.fr/

Sign up, then go here and upload competitions:
https://codalabcomp-v2-prod.lri.fr/competitions/upload/

Make submissions here (click `a` then `b`):
![image](https://user-images.githubusercontent.com/2185159/69003572-7ac62780-08b9-11ea-8f48-d71dc17b7b4b.png)

Submit submission to leaderboard (click `c`):
![image](https://user-images.githubusercontent.com/2185159/69003593-b6f98800-08b9-11ea-86be-453ed26c1730.png)

# Acceptance criteria

- [x] Competition uploads and unpacks properly
- [x] Submission uploads and runs properly
- [x] Submitting score to leaderboard works

**Comment by madclam** [comment]
There are some problems with the FILES tab, the pages, and the various editor options. To be handled at consolidation time.
