### ISSUE TITLE
Isabelle review: participant management

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#262]
# Participant Management

### If you find issues _not_ related to the participant manager, please open them as new _separate_ issues, not comments on this review

View a competition here: https://codalabcomp-v2-prod.lri.fr/competitions/11/#/participate-tab

If you follow the Login link, it should bring you back to this page afterword. The signup page should open in a new tab.

- [x] You should be able to view the competitions terms by clicking on `terms and conditions`

![image](https://user-images.githubusercontent.com/37089863/69103825-4a969a00-0a1b-11ea-8b63-334a1d15924a.png)

- [x] once logged in, you should have to check the `I agree to the terms` checkbox before the register button can be selected
- [x] selecting the Register button should create a registration request
- [ ] in the linked competition, registrations are auto-approved, so you should not need approval form administration
- [x] this competition: https://codalabcomp-v2-prod.lri.fr/competitions/14/#/participate-tab does not have auto approval, so once registering, you should see your registration status go to "pending" and can be approved or denied by the competition administration (admin or collaborators).

To create your own competition, click on the competition link in the header:
![image](https://user-images.githubusercontent.com/37089863/69096661-b7a13400-0a09-11ea-87c5-f84d483653b6.png)

Use this zip file:
[wheat_seed_competition.zip](https://github.com/codalab/competitions-v2/files/3861301/wheat_seed_competition.zip)
and click the `upload` button in the upper right or follow this link:
https://codalabcomp-v2-prod.lri.fr/competitions/upload/

from the competition detail page, click the teal gears to see a dropdown of admin management options: 
![image](https://user-images.githubusercontent.com/37089863/69105468-2ee1c280-0a20-11ea-9ff3-6b0a14202dcb.png)
(You must be logged in as the competition organizer to see this)

From the dropdown, select Manage Competition
![image](https://user-images.githubusercontent.com/37089863/69105513-5afd4380-0a20-11ea-8b08-e4fb57c97f8f.png)
A modal should appear with a blue `Edit Competition` button.

- [x] Clicking this should take you to the competition editor

- [x] Clicking on the "Participate" tab brings you to a page with a markdown editor for editing the terms and conditions of the competition, as well as a checkbox to toggle whether the competition should auto-approve participants.

Navigate back to your competition detail page.
Clicking the same teal gears, click on "Manage Participants"
![image](https://user-images.githubusercontent.com/37089863/69105911-a106d700-0a21-11ea-8a1e-604f8b1984f9.png)

This will bring up a modal with a table of all the participants of this competition
- [x] a search box allows you to search through the list of participants, both by email and by username. 
- [x] You can also filter the table with the status dropdown, to see only users w/ a specific participation status.
- [x] There is a large blue button next to the status dropdown that will let you email all the competition participants (this filters based on `status=Approved`).
- [x] This should bring up a modal that will let you write markdown content to send as an email to all participants in a competition.
- [x] the modal has a fixed subject `A message from the admins of <Competition Name>` and cannot, at this time, be changed
- [x] clicking the paper airplane button should send the email
- [x] clicking the trash can cancels sending the email
- [x] this bulk email is sent as bcc instead of cc, so recipients cannot see the emails of all participants
- [x] the participation table also has actions: approve, revoke, and send message.
- [x] Approve should be visible if the participant is not currently approved
- [x] revoke should be visible if the participant is not currently denied
- [x] send message should always be visible
- [x] clicking the send message button should bring up the same email modal as before, but this time the message will only be sent to the individual user.

**Comment by madclam** [comment]
- It should be possible to view the terms and conditions after having reviewed them.
- If I click register without being logged in I get an error:
<img width="435" alt="Screen Shot 2019-11-22 at 11 21 24 PM" src="https://user-images.githubusercontent.com/7594063/69464548-e5c2a300-0d7e-11ea-8735-7c0010e2d998.png">

**Comment by jimmykodes** [comment]
@madclam 
Thank you for the review.

I quickly addressed a few of your comments, so if you retest these specific issues, they should be working correctly now:

- [ ] in the editor, you should not need to click the box to see the rules
- [ ] you can not see a "register" button if you are not logged in, instead, there are links to "Login" and "Sign Up"
- [ ] in the editor, the "auto approve" checkbox should correctly reflect the state of the competition.

In regard to your other comments:
- I should be able to add the terms as another page in the "Get started" tab, below all the other pages.
- The "email all participants" button does send an email all participants, as you pointed out, since it is currently independent of the search results in the table. We may be able to add the functionality of only emailing the participants based on the search/filter selections, if there is a need for that.
- "forgot my password" is not related to participating in a competition, so is not addressed by participant management.

**Comment by madclam** [comment]
All passed. We'll address other issues separately.
