### ISSUE TITLE
Isabelle review: phase-to-phase migrations

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#263]
# Acceptance
- [x] Able to enable phase migrations in competition editor
- [ ] Phase does not migrate when it's already migrating
- [ ] Phase does not migrate when it is scoring submissions
- [x] Phase auto-migrates after date passes, submissions are run

**Comment by madclam** [comment]
Not possible to migrate by hand.

**Comment by ckcollab** [comment]
> _Could not get it to work by changing the date._

Which phase did you set to migrate? `auto_migrate_to` should be set on the phase to migrate _to_, not the phase to migrate _from._ Hope that makes sense.

**Comment by ckcollab** [comment]
TODO: Add video demonstrating this working

**Comment by madclam** [comment]
VIDEO is not needed. I understand what needs to be done, this is not the problem.

I created a collection of bundles to test V2.
V1 bundles can be found [here ](https://www.dropbox.com/sh/awgurohmkotmah2/AAD4AT_qxFFFyTqcx5mSoPuIa?dl=0)
V2 bundles can be found [here](https://www.dropbox.com/sh/u3ll441moumqhuh/AADH6_pX2Y86R3yUme8wJVX4a?dl=0) 

1) Cannot complete upload a bundles from v1: stuck at the unpack level. An example is

<img width="579" alt="Screen Shot 2019-11-27 at 8 08 38 PM" src="https://user-images.githubusercontent.com/7594063/69752780-4ae91080-1152-11ea-8185-5674e3cde622.png">
![Uploading Screen Shot 2019-11-27 at 8.02.53 PM.png…]()



2) Cannot complete

**Comment by jimmykodes** [comment]
The competition yaml of all v2 competitions needs to have `version: 2` in it, otherwise it attempts to unpack it as a v1.5 bundle (hence HTML pages being required). So your Iris competition and Sample competition will not upload correctly. The wheat seed competition _should_ upload correctly, though. 

Thank you for catching the error with dumps, looks like they are not including versions in their yaml files. I can fix this. In the mean time, you can open the dump competition yaml and add `version: 2` to it, and it should upload.

Can you be specific about which v1 bundle is getting stuck in unpack forever? I'd be happy to look in to it, but I need to know which bundle isn't working, or if all of them aren't working.

**Comment by madclam** [comment]
I do not know how to test:
 Phase does not migrate when it's already migrating
 Phase does not migrate when it is scoring submissions

In the future, for testing I suggest to provide:
1) the URL of the server to be tested
2) competition bundles that work
3) also website with the corresponding bundle already uploaded on which I am an admin
4) sample submissions that work
5) step-by-step instructions of what to do including screen shots if there is something tricky

**Comment by madclam** [comment]
> The competition yaml of all v2 competitions needs to have `version: 2` in it, otherwise it attempts to unpack it as a v1.5 bundle (hence HTML pages being required). So your Iris competition and Sample competition will not upload correctly. The wheat seed competition _should_ upload correctly, though.
> 
> Thank you for catching the error with dumps, looks like they are not including versions in their yaml files. I can fix this. In the mean time, you can open the dump competition yaml and add `version: 2` to it, and it should upload.
> 

I did that but then got another error:
<img width="573" alt="Screen Shot 2019-11-27 at 9 14 34 PM" src="https://user-images.githubusercontent.com/7594063/69756551-10d03c80-115b-11ea-9c0b-2f117385e32a.png">
Please test a bunch of dumps and re-upload them to make sure they work.

> Can you be specific about which v1 bundle is getting stuck in unpack forever? I'd be happy to look in to it, but I need to know which bundle isn't working, or if all of them aren't working.

Malaria detection challenge.zip
[from V1 bundles ](https://www.dropbox.com/sh/awgurohmkotmah2/AAD4AT_qxFFFyTqcx5mSoPuIa?dl=0)
