### ISSUE TITLE
Isabelle review: Queue Management

### ISSUE THREAD

**Issue by Tthomas63** [codalab/competitions-v2#264]
Login/Sign-up: https://codalabcomp-v2-prod.lri.fr
Files:
 - Competition Bundle with queue: https://drive.google.com/file/d/1FlgyDY5sIpgAOr1hfvA_9sWMmuHXzuA0/view?usp=sharing
 - Competition Bundle without queue: https://drive.google.com/file/d/1yPYp0dqKWjS2zbhS3i14kuMdh76qN57t/view?usp=sharing

Test User: test-user2019
Test Password: 0293d5a8-22e8-4a7f-843e-a498c12babc9

Access Queue Management from the main header menu:
![image](https://user-images.githubusercontent.com/28552312/69081474-e5c74980-09f2-11ea-9a68-82663c5aa5bd.png)
![image](https://user-images.githubusercontent.com/28552312/69103635-c3492680-0a1a-11ea-9df8-c5e1ae780345.png)

Verify the following is possible:
- [x] Create Queues
![image](https://user-images.githubusercontent.com/28552312/69103653-d22fd900-0a1a-11ea-9bee-2bacb47d6925.png)

- [x] Edit Queues
![image](https://user-images.githubusercontent.com/28552312/69103678-e378e580-0a1a-11ea-939a-69e463ac261f.png)

- [x] Delete Queues
![image](https://user-images.githubusercontent.com/28552312/69103742-115e2a00-0a1b-11ea-8433-c4e0c4c8787f.png)

- [x] Able to search Queues
![image](https://user-images.githubusercontent.com/28552312/69103715-fb506980-0a1a-11ea-9aaa-15fe9ca3676d.png)
![image](https://user-images.githubusercontent.com/28552312/69103729-04d9d180-0a1b-11ea-8a6d-c8f87cbecb6e.png)

- Navigate to a Competition, or create one:
With Queue: https://drive.google.com/file/d/1FlgyDY5sIpgAOr1hfvA_9sWMmuHXzuA0/view?usp=sharing
Without Queue: https://drive.google.com/file/d/1yPYp0dqKWjS2zbhS3i14kuMdh76qN57t/view?usp=sharing
- Goto the edit page for it, and stay on the main competition details. Edit the `Queue` field at the very bottom of the main competition details.
![image](https://user-images.githubusercontent.com/28552312/68381023-c7fe0880-0105-11ea-80cf-43af52c13c49.png)
- [x] Verify being able set a Queue, save and verify the changes held
- [x] Verify being able to un-set a Queue, save and verify the changes held
- [x] Verify uploading competition with queue sets queue correctly

**Comment by madclam** [comment]
Looks good!
I did not check we can hook up a compute worker to the queue.
