### ISSUE TITLE
Submission "Failed", no logs

### ISSUE THREAD

**Issue by Didayolo** [codalab/competitions-v2#279]
Hi,

Now I have this competition online: [Heart Attack Challenge (V2)](https://codalabcomp-v2-prod.lri.fr/competitions/32/?secret_key=0449c738-e215-45f0-b7ee-083b16e05cd7).

When I try to upload my baseline submission, the status returns "Failed".

No error message or log help me debugging, even with the administrator panel "manage submissions".

Also, the exact same submission works in the [Codalab V1 version of this challenge]( https://competitions.codalab.org/competitions/22204?secret_key=fcadbcdb-dec2-4b10-8399-941934e585a5).

**Comment by jimmykodes** [comment]
Can you provide the submission you attempted to run? I ran this submission without any errors

[submission.zip](https://github.com/codalab/competitions-v2/files/3984805/submission.zip)

**Comment by Didayolo** [comment]
It was "submission.zip" file. Indeed it is working.

This is strange! Maybe I've refresh the page during the uploading or preparation of the submission.

If I manage to reproduce the error I'll re-open this issue, but I guess there is nothing wrong.

Thanks again Jimmy!
