### ISSUE TITLE
Minor GUI issues

### ISSUE THREAD

**Issue by Didayolo** [codalab/competitions-v2#284]
- [ ] Participant name is not shown in the leaderboard next to score

![minor2](https://user-images.githubusercontent.com/11784999/72159079-ec9f8680-33bb-11ea-8327-13c80340c9ff.png)

</br>
</br>

* [ ] `See more competitions` button does nothing

![minor1](https://user-images.githubusercontent.com/11784999/72159076-ead5c300-33bb-11ea-9da1-f616666b8172.png)

**Comment by jimmykodes** [comment]
This should be addressed on production now. 
included participant username in leaderboard and removed the see more competitions links since it had no where to link to.
You may need to clear you browser cache for these changes to take effect.

**Comment by ckcollab** [comment]
Closing this as I believe it's fixed, please re-open if not!

**Comment by Didayolo** [comment]
Indeed the points are fixed.

About the `See more competitions` button, I think it'll be important in the future to have the competition listed somewhere!

**Comment by ckcollab** [comment]
That's a good point, created #326 for that
