### ISSUE TITLE
Task > Files: Server Error (500)

### ISSUE THREAD

**Issue by Didayolo** [codalab/competitions-v2#286]
When clicking on any file of a task, like this (e.g. _input_data_):

![taskerror1](https://user-images.githubusercontent.com/11784999/72809100-41b08780-3c5b-11ea-8bba-b3d8b4aba3e0.png)

I get the following error:

![taskerror2](https://user-images.githubusercontent.com/11784999/72809102-41b08780-3c5b-11ea-91a5-05dc73fe5b79.png)

**Comment by ckcollab** [comment]
Closing this as I believe it's fixed, please re-open if not!

**Comment by Didayolo** [comment]
I just tried and the issue is still there.

**Comment by jimmykodes** [comment]
This issue is now resolved on production. (may need to clear cache for change to take effect)
