### ISSUE TITLE
Field "version" missing after dump

### ISSUE THREAD

**Issue by Didayolo** [codalab/competitions-v2#287]
In YAML file we are supposed to add this line:

`version: 2`

To show that the bundle is in Codalab V2 format. But when dumping and downloading the bundle from the dump, this line is missing, causing the bundle to fail in some cases.

**Comment by jimmykodes** [comment]
This should be fixed on production now. You may need to clear you browser cache for these changes to take effect.

**Comment by ckcollab** [comment]
Closing this as I believe it's fixed, please re-open if not!
