### ISSUE TITLE
Impossible to change HTML pages order

### ISSUE THREAD

**Issue by Didayolo** [codalab/competitions-v2#288]
I am trying to change the order of a challenge's HTML pages in the EDIT menu:

![orderissue1](https://user-images.githubusercontent.com/11784999/72827662-7e8c7680-3c7b-11ea-80d4-7d6e7dd967ca.png)

The resulting order is not the desired one:

![orderissue2](https://user-images.githubusercontent.com/11784999/72827663-7e8c7680-3c7b-11ea-916c-61103848c975.png)

**Comment by jimmykodes** [comment]
This should be fixed on production now. You may need to clear you browser cache for these changes to take effect.

**Comment by ckcollab** [comment]
Closing this as I believe it's fixed, please re-open if not!
