### ISSUE TITLE
Fix Queue broker URL (clipboard and missing port)

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#333]
- [ ] Currently on the Queues page, the given broker URL does not contain the `RABBITMQ_PORT` like it should. See the worker status page (http://localhost:8000/server_status) for an example of how to get the port.
- [ ] ~The "Clipboard" button does not appear to work?~ Hide clipboard feature on non-SSL 

### clipboard
![image](https://user-images.githubusercontent.com/2185159/74880911-2780cc80-5321-11ea-87f7-2b620c5c5db7.png)

### broker url missing port
![image](https://user-images.githubusercontent.com/2185159/74881030-67e04a80-5321-11ea-95d2-e344954197e4.png)

**Comment by jimmykodes** [comment]
The clipboard button will not work unless the website has SSL setup (or if you are running it on localhost).

**Comment by ckcollab** [comment]
Ah, in that case maybe we should hide that on local/nonSSL?

**Comment by ckcollab** [comment]
Fixed this recently for magali
