### ISSUE TITLE
Forums

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#352]
### Overview
Forums will add the ability to have discussions about a competition. Forums are typically used to communicate with competition admins about issues with submissions, but are also great for guides, community teamwork, and brainstorming.
Codabench v1.5 for reference: 
https://github.com/codalab/codalab-competitions/tree/develop/codalab/apps/forums

### Tasks
- Create a new app at `/src/apps/forums`

### Discussion points
- Which tab location? EG: Figure 1
- Should failed submissions link to forums, if forums enabled for competition?
- Do we want a tagging system to differentiate between "Troubleshooting", "Guide", "Discussions", ect.
- Notification System
  - Users
    - In created threads
    - Threads they have posted in
    - All or just popular threads for competitions they are apart of?
  - Admins
    - Notifications by tag. Useful to respond quickly to posts marked as "Troubleshooting"
    - Notification for new threads

Figure 1:
<img width="1363" alt="Screen Shot 2020-08-20 at 7 28 16 AM" src="https://user-images.githubusercontent.com/16579931/90802828-ab197700-e2cc-11ea-948a-4dab46e280f6.png">

**Comment by ckcollab** [comment]
> Where to put forum tab

2 votes for Forum at the end of tabs
1-2 votes for Forum at the beginning of tabs


> Should failed submissions link to forums, if forums enabled for competition?

Helps users feel like they have an area to get help with their submission problem, specific to that competition.  Maybe 2 help links:
 1. "common Codalab Submission problems"
 1. "common <current competition> submission problems"

Maybe we should consider the idea of a "Knowledge base" -- can use a Wiki for this? Can have a "Frequently Asked Questions" page on the Wiki?

Maybe think about a "global thread" -- "global sticky." Thread that concerns all competitions, kind of like a FAQ.

> Do we want a tagging system to differentiate between "Troubleshooting", "Guide", "Discussions", ect.

Maybe examine Kaggle forum? https://www.kaggle.com/discussion

Maybe helpful to have a "global forum view."

Maybe have ability to upvote & rank "hot" topics. 

> [Notifications]

Sounds fine in general.

------------------

In general: lots of flexibility, add on. Do not spend a lot of extra time on this.

**Comment by Logan-Ruf** [comment]
There was a comment about how kaggle's forums have a good amount of activity. First incentivizing users to make good forum posts is good. Also kaggle's UI does a good job a showing posts on the page with the competition to increase click through to the forum.

<img width="1431" alt="Screen Shot 2020-08-20 at 11 20 02 AM" src="https://user-images.githubusercontent.com/16579931/90810029-37c93280-e2d7-11ea-9e48-cb524d06c958.png">

**Comment by ckcollab** [comment]
Consider using hierarchical posting style, so people in a thread can reply to a specific post in that thread, similar to Reddit/Kaggle
