### ISSUE TITLE
Fix formatting on toastr error message on comp detail page

### ISSUE THREAD

**Issue by jimmykodes** [codalab/competitions-v2#392]
<img width="562" alt="Screen Shot 2020-03-06 at 12 43 05 AM" src="https://user-images.githubusercontent.com/37089863/76007906-a64e3b80-5ec3-11ea-9a4c-c4ae367848fe.png">

If logged in as a collaborator on the competition, and you remove yourself from the collaborators section, save as draft (so you don't leave the page) and then make changes and try and save again, you no longer have permission to edit the comp, and you get a poorly formatted toastr error message back. Should fix the formatting (probably a result of a for loop over a string instead of a list)

**Comment by ckcollab** [comment]
@dde6khkg bumping this up
