### ISSUE TITLE
V2 not responding

### ISSUE THREAD

**Issue by madclam** [codalab/competitions-v2#404]
https://codalabcomp-v2-prod.lri.fr/competitions/18/#/pages-tab
http://134.158.74.226/competitions/60/#/phases-tab
<img width="849" alt="Screen Shot 2020-04-25 at 2 32 18 PM" src="https://user-images.githubusercontent.com/7594063/80291357-b0412d80-8701-11ea-871c-66a4ad73ba7f.png">

**Comment by ckcollab** [comment]
This should respond now.
