### ISSUE TITLE
ERROR: The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by msubglb** [codalab/competitions-v2#405]
We are testing Codalab/competitions-v2 on a locally hosted server. The following error shows up only when we upload a zipped file (competition bundle/submissions) from Windows client. But, it works fine from a Linux client.

**"The request signature we calculated does not match the signature you provided. Check your key and signing method."** 
Looking at the HTTP headers - it seems content-type request is the only difference. Appreciate any feedback on settings that could solve this issue.

~~~~~~~~~~~~~~~~~~~~~~~~~~~
Host: <deleted>:9000  ==> Request header for Linux
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/zip ==> Difference
Content-Length: 453717
Origin: http:// <deleted>:8000
Connection: keep-alive
Referer: http:// <deleted>:8000/competitions/upload/

~~~~~~~~~~~~~~~~~~~~~~~~~~~
HTTP/1.1 200 OK  => Works
Accept-Ranges: bytes
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://<deleted>:8000
Access-Control-Expose-Headers: Date, Etag, Server, Connection, Accept-Ranges, Content-Range, Content-Encoding, Content-Length, Content-Type, X-Amz-Request-Id
Content-Security-Policy: block-all-mixed-content
Server: Minio/RELEASE.2018-12-06T01-27-43Z (linux; amd64)
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Host: <deleted>:9000 ==> Request header for Windows
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-zip-compressed  => Difference
Content-Length: 453717
Origin: http://<deleted>:8000
Connection: keep-alive
Referer: http://<deleted>:8000/competitions/upload/
~~~~~~~~~~~~~~~~~~~~~~~~~~~
HTTP/1.1 403 Forbidden => Gives Error message
Accept-Ranges: bytes
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://<deleted>:8000
Access-Control-Expose-Headers: Date, Etag, Server, Connection, Accept-Ranges, Content-Range, Content-Encoding, Content-Length, Content-Type, X-Amz-Request-Id
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: Minio/RELEASE.2018-12-06T01-27-43Z (linux; amd64)

**Comment by msubglb** [comment]
Checking the content type and setting it to" application/zip" solved the issue.
File name ==> src/static/js/ours/client.js


               cont_type = false
                if (data_file.name.split('.').pop() == "zip") {
                    cont_type = "application/zip";
                }
                console.log(cont_type);

                return $.ajax({
                    type: 'PUT',
                    url: result.sassy_url,
                    data: data_file,
                    processData: false,
                    contentType: cont_type,

**Comment by ckcollab** [comment]
@msubglb would you mind making a PR with this change? thanks!

**Comment by msubglb** [comment]
Sure. I'll do it this weekend.
