### ISSUE TITLE
Task panel UI improvements

### ISSUE THREAD

**Issue by madclam** [codalab/competitions-v2#416]
Very often tasks carry the same name in several competitions. They all show up under the same name in the task panel. We need at least a column identifying their mother competition. We may need to think about some form of "name space".

<img width="1181" alt="Screen Shot 2020-06-08 at 9 36 43 AM" src="https://user-images.githubusercontent.com/7594063/84056798-95eaa880-a96b-11ea-8bbe-91dbc4941cb2.png">

**Comment by madclam** [comment]
A task cannot be downloaded as a single zip. Currently, you can download separately input data, reference data, scoring program and ingestion program.

<img width="900" alt="Screen Shot 2020-06-08 at 9 38 07 AM" src="https://user-images.githubusercontent.com/7594063/84057032-ebbf5080-a96b-11ea-97fb-456556140058.png">

**Comment by madclam** [comment]
Tasks should be sharable with other competition admins (add a "share button somewhere in the task admin panel"). This requires also adding another column in the panel identifying the owner and the sharing status.

**Comment by madclam** [comment]
The same applies to datasets and submissions. See the specs of the Cometh project.

![image](https://user-images.githubusercontent.com/7594063/101533921-510bf280-394b-11eb-896a-19cf0e96e7a4.png)
![image](https://user-images.githubusercontent.com/7594063/101533931-55381000-394b-11eb-94e7-4ccd390086e1.png)
![image](https://user-images.githubusercontent.com/7594063/101533964-5ec17800-394b-11eb-9b8f-08a829503c11.png)

Whenever a submission is run on a task, the tables will be updated to reflect this (Submissions associated, tasks associated, In use…). It will not be possible to:
- edit or delete a file used by a task or a submission
- delete a task used in a competition
- delete a submission that was submitted to a competition
- publish a task not validated by a submission 
- publish a submission not validated by a task
It should be possible to delete multiple files at the same time.

![image](https://user-images.githubusercontent.com/7594063/101534147-9d573280-394b-11eb-9713-b5f85d4e5283.png)

![image](https://user-images.githubusercontent.com/7594063/101534185-a8aa5e00-394b-11eb-8c1e-0547d93e6b51.png)

![image](https://user-images.githubusercontent.com/7594063/101534222-b3fd8980-394b-11eb-9823-b2dd8a3e8a75.png)

**Comment by madclam** [comment]
Fact sheets should be editable, see specs:

![image](https://user-images.githubusercontent.com/7594063/101534566-338b5880-394c-11eb-810b-a9419163998c.png)

**Comment by dde6khkg** [comment]
Benchmark names have been added to the task management table, and task sharing now works.
We're splitting the rest of this guy up into these smaller issues: #626 #627
