### ISSUE TITLE
Front end support for codabench project

### ISSUE THREAD

**Issue by AuroraLauu** [codalab/competitions-v2#418]
Hello there, This is Zhenwu from 4Paradigm, During the development of the Codabench project, most of our code was reused from existing code, so we needed front-end support for this.
The changes are divided into two main parts.
# 1. Modification of page content

- Benchmark’s page reuses the template associated with Competition. The text content on the page needs to be changed dynamically depending on the current url, as shown in the figure below.
![page content change 1](https://user-images.githubusercontent.com/50364579/84111652-fc4df480-aa59-11ea-88ba-3f92ae2a450a.jpg)
![page content change 2](https://user-images.githubusercontent.com/50364579/84111703-125bb500-aa5a-11ea-9f3a-4cfddfb19d40.jpg)
![page content change 3](https://user-images.githubusercontent.com/50364579/84111719-1ab3f000-aa5a-11ea-89f7-331da2e4d225.jpg)
![page content change 4](https://user-images.githubusercontent.com/50364579/84111730-20113a80-aa5a-11ea-9757-009d695549c3.jpg)

# 2. Modification of the backend API call for page buttons.

- When the corresponding button on the page is clicked, if the current page is under the benchmark, then should call the background benchmark related api, as shown in the following figure.
![page api change 1](https://user-images.githubusercontent.com/50364579/84111860-4df67f00-aa5a-11ea-8c41-2a3dd5dc1431.jpg)
![page api change 2](https://user-images.githubusercontent.com/50364579/84111863-5058d900-aa5a-11ea-94a7-f58961999c55.jpg)
![page api change 3](https://user-images.githubusercontent.com/50364579/84111867-52bb3300-aa5a-11ea-899b-716c1696bc91.jpg)
![page api change 4](https://user-images.githubusercontent.com/50364579/84111876-564eba00-aa5a-11ea-8960-856fd9e3b7d1.jpg)
![page api change 5](https://user-images.githubusercontent.com/50364579/84111934-6d8da780-aa5a-11ea-91cf-efe38e8d8a6a.jpg)
![page api change 7](https://user-images.githubusercontent.com/50364579/84112491-75018080-aa5b-11ea-82ba-1c2e2f2559ce.jpg)

**Comment by ckcollab** [comment]
TODO: Break into smaller issues, great outline though! ty for screenshots
