### ISSUE TITLE
Could not add submission result to Leaderboard after migrate

### ISSUE THREAD

**Issue by AuroraLauu** [codalab/competitions-v2#437]
# Problem 
![image](https://user-images.githubusercontent.com/50364579/85236658-6dc27580-b452-11ea-8cd3-9cabcd3ce714.png)

# Reproduce Step:
1. Create a competition
2. Upload a submission
3. Add current phase submission to leaderboard
4. Migrate
5. Add Final phase(which is migrate result to leaderboard)

# Error
Could not find a competition

# Backend logs
`django.db.utils.IntegrityError: duplicate key value violates unique constraint "competitions_submission_owner_id_leaderboard_id_a7fc5304_uniq"
DETAIL:  Key (owner_id, leaderboard_id)=(76, 58) already exists.`

**Comment by ckcollab** [comment]
Also relates to #459
