### ISSUE TITLE
HADACA competition issue

### ISSUE THREAD

**Issue by AuroraLauu** [codalab/competitions-v2#453]
# Problem Statement
Using the HADACA bundle from the dump to create the v2 contest, although the submission code can be created and submitted successfully, when running the submission, both Staging Server and Production Server show that the Scoring Program has finished and got the score, but the program does not exit, resulting in an Execution Time Limited exception.

URL:
production server: https://codalabcomp-v2-prod.lri.fr/competitions/75/#/participate-tab
staging server:  http://134.158.74.226/competitions/62/   (ps:Here's an even stranger phenomenon, Submission has set a timeout of 600 seconds, but it's been 5 hours since my commit time and it's still showing up running!)

# Console Output

production server:
ingestion program
![image](https://user-images.githubusercontent.com/50364579/86239695-63327980-bbd2-11ea-99d2-15e2f3a4d76c.png)

scoring program
![image](https://user-images.githubusercontent.com/50364579/86239749-79d8d080-bbd2-11ea-86a1-bc50701c9e4e.png)

error
![image](https://user-images.githubusercontent.com/50364579/86239867-aa206f00-bbd2-11ea-866a-13f12c822b55.png)

Staging Server:
ingestion program
![image](https://user-images.githubusercontent.com/50364579/86239805-937a1800-bbd2-11ea-8931-4812890e7ec4.png)

scoring program
![image](https://user-images.githubusercontent.com/50364579/86239832-9d038000-bbd2-11ea-853e-291eb7d7ecbc.png)

strange thing
![image](https://user-images.githubusercontent.com/50364579/86239945-d20fd280-bbd2-11ea-85f5-f6a7ab9b84d9.png)

Local Env：
When I try to start locally using the docker container, I find that the ingestion program fails to finish reading the dataset training model and somehow jumps to the scoring program, which directly causes the scoring program to crash.

![image](https://user-images.githubusercontent.com/50364579/86240159-3b8fe100-bbd3-11ea-9894-4959eee357ba.png)

**Comment by dde6khkg** [comment]
Looks like this is being caused by detailed results not being written to the correct spot. We're working on a fix now.
