### ISSUE TITLE
can't setup GPU queue in V2

### ISSUE THREAD

**Issue by NehzUx** [codalab/competitions-v2#467]
Hi,

I try to set up a GPU queue in v2 but failed as below.

Queue creation in v2: (https://codalabcomp-v2-prod.lri.fr/queues/)
![image](https://user-images.githubusercontent.com/12370705/87060459-2521ff00-c23d-11ea-8e23-3223c9b2ed82.png)
![image](https://user-images.githubusercontent.com/12370705/87060482-2c490d00-c23d-11ea-8053-5a96b30f8512.png)

In google cloud, I use the following command to run compute_worker:

`docker run -v /var/run/docker.sock:/var/run/docker.sock \
--env BROKER_URL=pyamqp://88226e49-d83c-443a-bc31-85031c44cf8c:f8c87936-ed13-478f-8fb3-985805124076@codalabcomp-v2-prod.lri.fr/156b045a-ebef-45b2-bc6a-8c2c2a7acb20 \
-d \
--restart unless-stopped \
--log-opt max-size=1m \
--log-opt max-file=3 \
--env BROKER_USE_SSL=True \
codalab/competitions-v2-compute-worker`

The logs of the container reports:

`[2020-07-09 15:34:44,311: ERROR/MainProcess] consumer: Cannot connect to amqp://88226e49-d83c-443a-bc31-85031c44cf8c:**@codalabcomp-v2-prod.l
ri.fr:5671/156b045a-ebef-45b2-bc6a-8c2c2a7acb20: [Errno 111] Connection refused.
Trying again in 6.00 seconds...`

**Comment by dde6khkg** [comment]
Looks like we left out the port number on the broker URL. It should be working now if you re-copy the url.

Closing this issue.
