### ISSUE TITLE
leaderboard doesn't render multiple tasks per submission

### ISSUE THREAD

**Issue by dde6khkg** [codalab/competitions-v2#479]
The leaderboard should display results for every task in a phase. It currently only displays results for one task.

![image](https://user-images.githubusercontent.com/39388873/88105876-72fe0780-cb59-11ea-8579-d08acdaf207e.png)

**Comment by Logan-Ruf** [comment]
If there are multiple tasks, submission children will now be added to each leaderboard.
TODO:
- Add functionality to "Add to Leaderboard" button to turn into check mark on competitions with multiple tasks
- Fix not being able to remove a submission from leaderboard

**Comment by Logan-Ruf** [comment]
This might be a fix for #465 as well.
