### ISSUE TITLE
Dump problem

### ISSUE THREAD

**Issue by madclam** [codalab/competitions-v2#485]
in https://codalabcomp-v2-prod.lri.fr/competitions/106/
create competition dump does not work:
<img width="360" alt="Screen Shot 2020-08-04 at 9 02 15 AM" src="https://user-images.githubusercontent.com/7594063/89333264-9640b080-d649-11ea-8e04-6fe30fcdee00.png">

**Comment by dde6khkg** [comment]
Looks like this guy is working on prod after recent fixes.
