### ISSUE TITLE
Ability to re-order Tasks (i.e. to get leaderboard columns in some specific order)

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#496]
![image](https://user-images.githubusercontent.com/2185159/90154510-0e406200-dd3f-11ea-87ce-9b06988a8c58.png)

Instead of ordered by pk 28, 29, 30 -- maybe make a new model `TaskInstance` where we  can have extra metadata like `index` to order these tasks

Organizers would set this ordering, not participants.

**Comment by Logan-Ruf** [comment]
![image](https://user-images.githubusercontent.com/16579931/93391124-8d83f280-f823-11ea-9b63-76c3f14d981b.png)
Since we only have the ability to have one leaderboard for a competition. Should I change repurpose this tab to be where an admin can change the order of tasks?
