### ISSUE TITLE
User Profiles (and Organizations) Spec

### ISSUE THREAD

**Issue by Logan-Ruf** [codalab/competitions-v2#502]
### Overview
User profiles stores personal information, but only a UserID and Email is required. These profiles can for a person, or for an organization to allow participation as a group.
#### Details:
- **User profile:** The current version of Codalab v2 does not allow users to edit their profile. This functionality will be implemented (Figure 3). Integration of user accounts on different components (CodaBench, Codalab, ChaGrade) will be supported if needed. User’s profiles will include (* means mandatory; to protect anonymity, only a contact email is required to identify users)
- **Organizations as User:** This will allow users to organize competitions and participate in them as a group. However, being a member of an organization is not mandatory to organize/participate a challenge/benchmark. This will also allow the platform to give credits to organization members for organizing competitions or participating in them (in their visible profile). To claim organizing a challenge or participating in it, an organization member will need to have been a member of that organization at least some time during the active period of the competition. This feature could replace both the notion of teams and of admins. To avoid sharing passwords, a member of an organization, logged in with his own personal ID, could switch to any organization he/she is a member of. 
- **Meta-users** (platform administrators) will be granted the right to impersonate users. 

### Tasks
- User ID *: cannot be changed
- Display name *: To be shown on leaderboard and profile page; by default, show the user ID; this can be changed
- Contact Person Email *: can be changed
- Contact Person First Name: optional
- Contact Person Last Name: optional
- Contact Person Title: optional
- Affiliation or Organization Name: optional
- Picture: optional (personal photo or organization logo)
- Description: optional
- Links to websites and social media: optional
- is_organization? Check-box
  - Editable list of current organization members: provide Codalab IDs of organization 
members
  - Non-editable list of former organization members (and dates start-end)
  - Choice of benchmarks and competitions co-organized to show on profile (check/uncheck) any organization member of a competition can add a competition in this list
  - Choice of benchmarks and competitions in which participated and rank/number of 
participants – any organization member of a competition can add a competition in this list
- Opt-in/out to receive emails (to respect GDPR).
### Discussion points
- Have base Profile object extended by User and Organization objects. Users and Organizations would share a lot of features, but would have more differentiation.

**Comment by ckcollab** [comment]
### Isabelle:
> Create an Organization as a "Group" and the group has an email -- like Google Groups, we should probably stick with Google Groups.

A big concern is email, <some generated email>@codabench.org

**Consider "rights" to things:**
 - Competition collaborators
 - Queue collaborators
 - Datasets
 
Maybe like Unix concept of Permissions Groups? "Permission Group" isn't an entity, but a set of people. 

Roles in Permissions Groups? Like Admin vs User in group. "Who is allowed to do what?" and "Who is allowed to change permissions?"

**Some use cases:**
 - Share data
 - Run a class and setup multiple teams in your competition


**vs Kaggle groups:**
 - _not ideal_
 - Groups are formed by competition
 - Within a competition they are mutually exclusive
 - First person in group can invite others
 - "Groups" used to rate people, some credit for participating in a group that wins/gets points
 - _(in Codalab people allowed to have multiple accounts, Kaggle only allows 1 -- "witch hunting" for cheating)_

**Comment by ckcollab** [comment]
Consider this:
 - User makes submission to competition, no group, submission just attached to user
 - User joins a group, does the previous submission become a "submission of that group?"

Google groups permissions matrix
![image](https://user-images.githubusercontent.com/2185159/90808061-4d892880-e2d4-11ea-967e-cc9733573326.png)

**Comment by Logan-Ruf** [comment]
Considering a future point system. It would make sense for a user to change a submission from being from on the user to a group. But we restrict users from moving a group submission to a user. If we don't a user could take a submission from the team for themselves.
