### ISSUE TITLE
Competition Edit, phase dates duplicates between phases

### ISSUE THREAD

**Issue by Logan-Ruf** [codalab/competitions-v2#503]
If you try to change the start and end dates on multiple phases without reloading the page, it will duplicate the dates to all phases you try to edit.

![image](https://user-images.githubusercontent.com/16579931/90837459-f81a3f00-e306-11ea-8bf0-a1e4cee87411.png)

**Comment by gibsonbailey** [comment]
Fixed in PR #506.
