### ISSUE TITLE
[Leaderboard] Allow participants to submit submissions for review by organizers (organizers decide whether to hide/show them)

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#511]
Maybe one way to accomplish this would be all submissions appear on leaderboard "grayed out" with some button to "approve" them. 

Only admins/collabs could see + hit this "approve" button. Once approved they become viewable by public.

Grayed out submissions are hidden from public view.

**Comment by Logan-Ruf** [comment]
Should this follow the current system where users can add only 1 submission to the leaderboard?

**Comment by Logan-Ruf** [comment]
@magrichard Do you need this, or is what we have so far good?

**Comment by magrichard** [comment]
Hi @Logan-Ruf, I don't think this option is urgent, as it is allows possible for an organizer to remove a submission from the leaderboard.
