### ISSUE TITLE
Recurrent error from Flower

### ISSUE THREAD

**Issue by JulienNauroy** [codalab/competitions-v2#523]
Hi,

I'm trying to make Codalab work on a VM.
After running "docker-compose up" without the "-d" to get all the output, I noticed there's a recurring error from Flower (see below). Happens in the "development" as well as the "master" branch. Do you know how it can be fixed?

flower_1          | Traceback (most recent call last):
flower_1          |   File "/usr/local/bin/flower", line 5, in <module>
flower_1          |     from flower.__main__ import main
flower_1          |   File "/usr/local/lib/python3.8/site-packages/flower/__main__.py", line 4, in <module>
flower_1          |     from flower.command import FlowerCommand
flower_1          |   File "/usr/local/lib/python3.8/site-packages/flower/command.py", line 17, in <module>
flower_1          |     from celery.bin.base import Command
flower_1          | ImportError: cannot import name 'Command' from 'celery.bin.base' (/usr/local/lib/python3.8/site-packages/celery/bin/base.py)

**Comment by Logan-Ruf** [comment]
Thanks for noticing that! It's on our todo list, but the project should work fine as is.

**Comment by ckcollab** [comment]
Seems to load OK for me now? maybe try `docker-compose up -d --build` for a fresh test? what is your `FLOWER_PUBLIC_PORT`?
