### ISSUE TITLE
Name of submissions: missing?

### ISSUE THREAD

**Issue by magrichard** [codalab/competitions-v2#538]
We need to be able to add a meaningful name to submissions (in addition to the automatic labels 'File Name' and 'Username'). This name should appear on the leaderboard (in addition to or instead of Username)

**Comment by Logan-Ruf** [comment]
Hello, I've been working on an update to the Fact Sheet system for v2. This system allows you to set questions to be attached to submissions. You can see the details in the PR #553. Does this solve your problem?

**Comment by magrichard** [comment]
Hello @Logan-Ruf , 
I am not sure to understant how the Fact Sheet system works. Where can I find the factsheet edit form? How can I specify it?
Thank you very much.

**Comment by magrichard** [comment]
Hi again, I found the fact sheet editor... 
Seems to work pretty well, thank you!

However, I noticed that the metadata do not appear on the leaderboard .json file.

The idea would be to be able to identify different submissions when multiple submissions from a single user will be allowed on the leaderboard (I had a look on PR#542, looks good also!). What are your thoughts about this?

**Comment by Logan-Ruf** [comment]
Thanks for pointing that out. The issue should be fixed now.
