### ISSUE TITLE
Possibility to add several submissions to the leaderboard

### ISSUE THREAD

**Issue by magrichard** [codalab/competitions-v2#539]
Participants should be able to put several submissions on the leaderboard. For the COMETH project, I will submit several reference dataset and I want them to appear on the leaderboard (with meaningful names, see issue #538)
I thought a temporary solution would be to create as many user accounts as reference datasets, however, as creation of a new user account requires a unique email adress identifier, it is not an option.

**Comment by Logan-Ruf** [comment]
This problem is almost done being worked on. Updates can be found at PR #542. Let me know if you have any questions.

**Comment by magrichard** [comment]
Dear @Logan-Ruf,

I am not sure to understand how multiple submissions are now working. Is the functionality implemented yet?
Thank you!

Magali

**Comment by Logan-Ruf** [comment]
Yes, it is! Here's a little guide on how to change the settings on www.codabench.org in case someone else also has this question.

In the competition edit page, go to the leaderboard tab and edit the leaderboard.
<img width="890" alt="Screen Shot 2020-12-01 at 10 36 27 AM" src="https://user-images.githubusercontent.com/16579931/100782812-cf9fe780-33c1-11eb-9c62-cd6d2a36e475.png">

Next, change the submission rule to `Add and Delete Multiple` and save the leaderboard.
<img width="1069" alt="Screen Shot 2020-12-01 at 10 37 13 AM" src="https://user-images.githubusercontent.com/16579931/100782937-fc53ff00-33c1-11eb-84cb-dfe1a9385ff2.png">

Now save the competition.
<img width="866" alt="Screen Shot 2020-12-01 at 10 38 14 AM" src="https://user-images.githubusercontent.com/16579931/100782967-04ac3a00-33c2-11eb-89a4-c8ca22bee02d.png">

Now you should be able to add multiple submissions to the leaderboard. You can also remove a submission from the leaderboard by pressing the green checkmark.
<img width="1209" alt="Screen Shot 2020-12-01 at 10 39 04 AM" src="https://user-images.githubusercontent.com/16579931/100782986-0c6bde80-33c2-11eb-9565-566202a96ebe.png">

<img width="1196" alt="Screen Shot 2020-12-01 at 10 39 09 AM" src="https://user-images.githubusercontent.com/16579931/100783086-2f968e00-33c2-11eb-9aab-13e385cd193b.png">

**Comment by magrichard** [comment]
Wonderful :)
Thanks @Logan-Ruf
