### ISSUE TITLE
bot-submission: can't submit to specific tasks

### ISSUE THREAD

**Issue by magrichard** [codalab/competitions-v2#555]
Error in specifying a task list in the example_submission.py script, according to the wiki:
"TASK_LIST can be used to submit to specific tasks on a phase. If left blank, the submission will run on all tasks."

If specifying a string :  task_list = ["123"] -> the run fails
If specifying a number :  task_list = [123] -> all task are run

**Comment by Logan-Ruf** [comment]
I've tested this locally and on develop and it is working as expected. I would double check the id's you are submitting to. If you are still having troubles could I get the phase id and task id's you are trying to use so I can test them specifically?
