### ISSUE TITLE
Creation of a new queue: 'An error occured'

### ISSUE THREAD

**Issue by magrichard** [codalab/competitions-v2#556]
When trying to create a new queue, clicking the submit button leads to an error message:

![Capture d’écran 2020-11-10 à 13 49 30](https://user-images.githubusercontent.com/18577578/98676228-9abce980-235b-11eb-8250-2af2d8a336f5.png)

**Comment by ckcollab** [comment]
@magrichard please give this a shot now, should be working!

**Comment by magrichard** [comment]
Yes. Thank you!
