### ISSUE TITLE
Confirm fact sheets required fields are entered before allowing submission upload to proceed

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#575]
![image](https://user-images.githubusercontent.com/2185159/100904397-d854f400-347b-11eb-843b-9ef8c9a72bcc.png)

Maybe the upload file field input should be disabled until required form fields are entered?

**Comment by dde6khkg** [comment]
This seems to be fixed. Closing now.

![image](https://user-images.githubusercontent.com/39388873/103384843-c4b5a100-4aac-11eb-82aa-ecc64a615369.png)
