### ISSUE TITLE
adding extra column submmsion id for leaderboard

### ISSUE THREAD

**Issue by AuroraLauu** [codalab/competitions-v2#578]
**issue we are facing**:
When we enable adding all Submissions to the LeaderBoard, we can't tell which Submissions belong to which. 
![image](https://user-images.githubusercontent.com/50364579/101130710-ed2db500-363e-11eb-862e-23925bb0d016.png)

**possibile solutions**:
Therefore, we need to add a column of Submission IDs to tell the user which Submissions the current score belongs to.
![image](https://user-images.githubusercontent.com/50364579/101130814-2403cb00-363f-11eb-85d0-09a24d775795.png)

Likewise, we would like to know exactly what algorithm ran these scores, and it would be a good idea to use the Submission filename as the default.
![image](https://user-images.githubusercontent.com/50364579/101131130-c02dd200-363f-11eb-804e-97e284d807ee.png)

For the back-end part, @AuroraLauu will take care of this and return additional fields (submmision_id, algorithm_name) to the frontend, and the frontend just needs to display them.

**Comment by magrichard** [comment]
Dear @AuroraLauu , 

This has been solved already.
By editing a factsheet in the Edit>Details menu, you can add metadata that will automatically appear on the leaderboard enabling the identification of different submissions coming from the same user. See screenshots below as an example:

Editing FACTSHEET in the details menu:
![Capture d’écran 2020-12-04 à 09 13 15](https://user-images.githubusercontent.com/18577578/101139086-51d21b00-3611-11eb-864e-00288bbd953e.png)

Corresponding factsheet metadata on the leaderboard
![Capture d’écran 2020-12-04 à 09 13 28](https://user-images.githubusercontent.com/18577578/101139094-54347500-3611-11eb-9edd-284d53f2137e.png)

**Comment by AuroraLauu** [comment]
> Dear @AuroraLauu ,
> 
> This has been solved already.
> By editing a factsheet in the Edit>Details menu, you can add metadata that will automatically appear on the leaderboard enabling the identification of different submissions coming from the same user. See screenshots below as an example:
> 
> Editing FACTSHEET in the details menu:
> ![Capture d’écran 2020-12-04 à 09 13 15](https://user-images.githubusercontent.com/18577578/101139086-51d21b00-3611-11eb-864e-00288bbd953e.png)
> 
> Corresponding factsheet metadata on the leaderboard
> ![Capture d’écran 2020-12-04 à 09 13 28](https://user-images.githubusercontent.com/18577578/101139094-54347500-3611-11eb-9edd-284d53f2137e.png)

wow this is awesome，I also tried it and it worked great, thank you for your answer!
![image](https://user-images.githubusercontent.com/50364579/101143071-6209ea80-3651-11eb-8c3b-5ccc699d8266.png)
