### ISSUE TITLE
ordering task by id on leaderboard display

### ISSUE THREAD

**Issue by AuroraLauu** [codalab/competitions-v2#579]
**issue we are facing:**
The display order of tasks on the LeaderBoard is Second Task, Third Task, First Task, which looks strange.
![image](https://user-images.githubusercontent.com/50364579/101131779-d2f4d680-3640-11eb-9096-53c35836ba83.png)

Try to open the chrome console to see the api return value and find that the minimum task id is First Task.
![image](https://user-images.githubusercontent.com/50364579/101131604-890bf080-3640-11eb-96a8-a75394f2b201.png)

**possible solution:**
Is it possible for the front end to sort the tasks according to their task ids so that the display of the leaderboard will look more reasonable.

**Comment by Logan-Ruf** [comment]
Order can be set by in the competition edit screen under Phase>Edit>Tasks. I did just add a secondary order by Task_ID if this is not set. This update should be reflected on the live website by the end of the week.
<img width="868" alt="image" src="https://user-images.githubusercontent.com/16579931/101526332-4e0c0480-3941-11eb-9f27-8ca35a88d8b8.png">
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/16579931/101527787-4e0d0400-3943-11eb-8031-3f55285cd36f.png">
