### ISSUE TITLE
Mapping Codalab competition-v2 port from 8000 to 80

### ISSUE THREAD

**Issue by ashwini-kr-sharma** [codalab/competitions-v2#584]
I have installed an instance of Codalab Competition-v2 in our institute's cloud VM and if I `ssh` to my VM with a running Codalab v2 instance via port forwarding like this -

`ssh -L 8000:localhost:8000 -L 8010:localhost:9000 ubuntu@172.16.114.203`

 I am able to see the Codalab V2 and Minio webpage through my local machine browser at `localhost:8000` and `localhost:8010` respectively.

This VM also has an associated public IP address and now I want to make a running instance viewable publically from a local browser. Our cloud admin told me that only those web-apps running on port 80 is viewable publically with the associated public IP address. For example, a simple Apache webserver on port 80 was viewable at the public IP.

I was wondering if it is possible to map the output port of Codalab V2 from 8000 to 80? My naive attempts to change the port configuration in the `docker-compose.yml` file created port conflicts and were not successful.

**Comment by ckcollab** [comment]
Is the `caddy` service running on the machine and serving on `80`? You could try commenting out that service and then changing the port should not have conflicts.

**Comment by ashwini-kr-sharma** [comment]
Your solution worked like a charm !! I have been struggling with this for weeks, can't thank you enough. 

I just had to run `docker-compose` again with the `--remove-orphans` flag to remove orphan containers for Caddy.

**Comment by ckcollab** [comment]
Awesome, glad to help!! :)
