### ISSUE TITLE
Dump not working

### ISSUE THREAD

**Issue by madclam** [codalab/competitions-v2#586]
I tried to dump my competition from 2 test competitions:
https://www.codabench.org/competitions/197/
https://www.codabench.org/competitions/198/

I can get the original bundle, but not a modified version from the editor.

**Comment by madclam** [comment]
I close another dump issue. But not sure whether this other one was addressed:
https://github.com/codalab/competitions-v2/issues/415

**Comment by ckcollab** [comment]
This problem appeared from a refactor, I just pushed a fix for this and tested on 197. I'll add an issue (#590) for writing a comprehensive dump test so we don't run into this again as easily.
