### ISSUE TITLE
Submissions status is finished while task are still running

### ISSUE THREAD

**Issue by magrichard** [codalab/competitions-v2#587]
Hi,

I made a submission on competition #199 (1 phase, 12 tasks).
I made a submission against 2 tasks (MT1 and MT2).
I noticed that my submission was announced finished while task 2 (MT2) is not over (prediction step still running). I was even able to put the results on the leaderboard:

![Capture d’écran 2020-12-08 à 14 13 24](https://user-images.githubusercontent.com/18577578/101488234-a3efa500-395f-11eb-8315-62eaa9cf09c9.png)

While I am writing this message, tasks 2 is still in progress. Refreshing the page doesn't change the submission status.

**Comment by magrichard** [comment]
update 24h hours later: task 2 (MT2) seems to be blocked while executing the prediction program.
No error appeared in the prediction logs.
The prediction output is not downloadable.
Submissioon status still indicates 'finished'

**Comment by magrichard** [comment]
By looking at the server status, I jsut saw that this submission (#1675) appears as 'failed'. But it seems impossible to retrieve this information on the regular web interface, neither to know the cause of the failure

**Comment by ckcollab** [comment]
Resolving these bad statuses here:
https://github.com/codalab/competitions-v2/issues/608
