### ISSUE TITLE
Submission blocked

### ISSUE THREAD

**Issue by magrichard** [codalab/competitions-v2#594]
I made a submission yesterday on the competition #199 -> submission ID : 1676
The submission file (dataset) was long to upload (1,77 Go).
I have the feeling that everything is blocked now. When I refresh the page, I get the following informations:
- 'Uploading' status in the information banner 
![Capture d’écran 2020-12-09 à 09 32 14](https://user-images.githubusercontent.com/18577578/101606091-4319a880-3a03-11eb-92cc-b2e609555eb7.png)

- 'Running' status in the submission table
![Capture d’écran 2020-12-09 à 09 32 20](https://user-images.githubusercontent.com/18577578/101606117-4c0a7a00-3a03-11eb-9eca-e0fd1c918bbb.png)

- 'Blank field' when I click on the submission to get more information from the 'user' interface
![Capture d’écran 2020-12-09 à 09 32 24](https://user-images.githubusercontent.com/18577578/101606136-50369780-3a03-11eb-8227-83dba234755b.png)

- 'Blank field' when I click on the submission to get more information from the 'admin' interface
![Capture d’écran 2020-12-09 à 09 41 45](https://user-images.githubusercontent.com/18577578/101606177-5cbaf000-3a03-11eb-9580-7dcbdadcd29e.png)

- 'Running' when I look at the server status (the parent submission occured 13h ago, but apperenlty the children tasks have not been created yet)
![Capture d’écran 2020-12-09 à 09 43 28](https://user-images.githubusercontent.com/18577578/101606213-66dcee80-3a03-11eb-9b35-900918c356b3.png)

**Comment by ckcollab** [comment]
What are the required specs for compute workers for your competition? If you have any compute workers connected to a queue, make sure they are using the latest image

**Comment by magrichard** [comment]
So far we are using the default public queue. @ashwini-kr-sharma didn't succeed yet to set up compute workers (still dealing with the following issue:  https://github.com/codalab/competitions-v2/issues/566).

I am not sure to understand what you mean by 'required specs' for compute workers...

**Comment by ckcollab** [comment]
@magrichard sorry, to be clearer: what are the minimum compute resources to run this 1.7gb submission -- i.e. CPU, Ram, Storage space? It looks like part of the problem was the workers only have ~15gb available to run jobs at the moment

**Comment by magrichard** [comment]
Hi @ckcollab,

I would say, for our benchmark codabench:
8G ram per CPU, 50G storage space to be safe (25G minimun).
1CPU per worker is enough, as our computational methods are not set up to use parallel computing.

Does it seems feasible?

Thanks!

FYI, the submissions you launched 18 hours ago (competition #199, parent submission #1692) are still running according to server_status, but no logs are printed out (for none of the tasks) when I try to follow the runs on the regular web interface

**Comment by ckcollab** [comment]
![image](https://user-images.githubusercontent.com/2185159/101950109-92014280-3ba9-11eb-86df-697321b505c4.png)

Submission finally finished after ~10hours on my machine...! I bet it will work once we have workers with more storage.
