### ISSUE TITLE
Submission stuck in scoring mode

### ISSUE THREAD

**Issue by madclam** [codalab/competitions-v2#597]
Competition
https://www.codabench.org/competitions/198
Submission:
https://newcodalab.lri.fr/coda-v2-prod-private/dataset/2020-12-08-1607406059/af0add476a51/iris_sample_code_submission.zip?AWSAccessKeyId=AZIAIOSAODNN7EX123LE&Signature=6W8BX6DkhyHCNZE%2FXSGJaP3fcK0%3D&Expires=1607731670

which was working yesterday is now stuck in scoring mode.

**Comment by ckcollab** [comment]
I ran the sample code submission and things went through OK for the moment, closing this as we have a few issues relating to submission status problems
