### ISSUE TITLE
Test Codabench on Windows Edge

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#599]

**Comment by NehzUx** [comment]
Still have this problem

![image](https://user-images.githubusercontent.com/12370705/103622625-f2e62580-4f71-11eb-94fb-b059e99a13f1.png)

**Comment by ckcollab** [comment]
We'll look at this more today, definitely a strange problem..

**Comment by ckcollab** [comment]
OK! Found the problem: Windows machines send a different content type, should be fixed very soon on prod
