### ISSUE TITLE
Fatal error with own compute worker

### ISSUE THREAD

**Issue by magrichard** [codalab/competitions-v2#602]
Hello,

Ashwin managed to set up a compute worker with this help of @ckcollab .

I created a public competition (#218) using the corresponding queue (i.e. codabench_queue_test).
I tried a submission and I got this error logs:

Fatal error: cannot open file '/app/program/ingestion.R': No such file or directory
Fatal error: cannot open file '/app/program/scoring.R': No such file or directory

Could you help us?

Thank you very much

**Comment by ckcollab** [comment]
You will need to update the compute workers (`docker pull codalab/competitions-v2-compute-worker:latest`) and also add this environment variable to the `.env` configuration file: `HOST_DIRECTORY`.

The instructions in the README here have been updated:
https://github.com/codalab/competitions-v2#worker-setup
