### ISSUE TITLE
Rerun submission automatically run against all tasks

### ISSUE THREAD

**Issue by magrichard** [codalab/competitions-v2#604]
Rerun submission (in admin mode) automatically runs the submission against all tasks.
Eventhough initially the initial submission was run only again a subset of tasks.

**Comment by Logan-Ruf** [comment]
Just tested this on development. Rerun a submission from these endpoints will check what tasks the original submission was run against. Is there a specific competition that you are having this problem with?
![image](https://user-images.githubusercontent.com/16579931/103249743-85107d00-4925-11eb-8fb6-6d54fff72232.png)
Results in:
![image](https://user-images.githubusercontent.com/16579931/103249843-fc461100-4925-11eb-8f81-98086690e348.png)
