### ISSUE TITLE
Auto Submission Rule is not working on production serevr

### ISSUE THREAD

**Issue by AuroraLauu** [codalab/competitions-v2#607]
# Problem Description
Try to enable one of the following three modes on the production server
![image](https://user-images.githubusercontent.com/50364579/102434464-c6fd1180-404f-11eb-92b5-77f3baaeef1c.png)
According to the expectation, it should be added to the LeaderBoard automatically when the Submission is completed, but the actual result is not.
We still need to manually add the Submission to the LeaderBoard ourselves.

# Local debugging results
- Pull develop branch code to local
- Upload bundle and enable `Force_Last/Force_Latest_Multiple/Force_Best` mode in the editor
- Try to submit multiple Submissions
- `Force_Last/Force_Latest_Multiple/Force_Best` mode work perfectly on local docker container

# Conclusion
- Auto Submission Rules `Force_Last/Force_Latest_Multiple/Force_Best` work perfectly on local but not on production serevr

Hello @ckcollab , Is there something we have set in production mode that is causing it to fail to take effect?

**Comment by ckcollab** [comment]
Do we have tests for these cases already? I'm not sure off the top of my head of any settings that would make this behave differently..

**Comment by AuroraLauu** [comment]
it works perfect on production server right now, gonna closed this issue
