### ISSUE TITLE
The production server cannot pull the image properly

### ISSUE THREAD

**Issue by AuroraLauu** [codalab/competitions-v2#615]
**Problem Description**
- When I tried to build a gpu type competition in the production server, the submission failed with an exception message that the docker image could not be pulled.The exceptions are as follows.
![image](https://user-images.githubusercontent.com/50364579/103262197-1ee83080-49df-11eb-8f7e-eee67ed0ca0c.png)
- To ensure that the docker image is downloadable correctly, I tested the pull docker image on my local machine and it downloaded correctly.
![image](https://user-images.githubusercontent.com/50364579/103262254-62db3580-49df-11eb-9675-f8e69aaef37b.png)

@ckcollab I will send you the bundle and submission in the slack.

**Comment by ckcollab** [comment]
Which queue did you run this on? Can you set your own machine as a compute worker and point it at a new queue for this competition? that way you can easily see the logs and manipulate the compute worker

**Comment by ckcollab** [comment]
is this resolved @NehzUx?

**Comment by NehzUx** [comment]
I think this is related to #630 . I close this issue for the moment.
