### ISSUE TITLE
How 'required' fact sheet items should be handled during bot submissions?

### ISSUE THREAD

**Issue by magrichard** [codalab/competitions-v2#622]
Dear all,

First of all: happy new year to all of you!

I was wondering how fact sheet information are handled during bot-submissions.

I tested this using competition #218, with submission_id fact sheet field being required for submissions.

When I submit on line as a regular user, the field submission_id is mandatory (as expected).

However, bot-submissions seem to be properly executed without further specification of a submission_id. I don't know if this is a bug or not, but it would make sense to me to leave it like this (bot submission should be as generic as possible). 

What are your thoughts about this?

Thanks

**Comment by Logan-Ruf** [comment]
Thanks for noticing that! It looks like the submission script submits the set the `fact_sheet_answers` to `NULL`, which prevents the answers from being validated. The front-end will always submit the `fact_sheet_answers` with some answer. If this works well, we can probably leave it as is. Any thoughts @ckcollab
