### ISSUE TITLE
Analytics page wireframes

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#63]
Should show the currently overall stats, like:

- Total # of users
- Total # of public competitions
- Total # of submissions

Then a breakdown per year, per month... maybe like a tab for each year:

2015 - 2016 - 2017 - 2018

Then under each tab breakdowns

Month | New user signups | New public competitions | New submissions
--- | --- | --- | --- 
January | 1 | 1 | 1
Feb | 1 | 5 | 100

**Comment by Tthomas63** [comment]
```
Broad statistics: The effectiveness of the new tools will need to be monitored with quantitative metrics.
To that end, admin tools will be augmented by usage monitoring, including number of new challenges
created, submissions made, new users, per month. Usage statistics will be summarizes on the front page
of Codalab and ChaHub.
```

**Comment by ckcollab** [comment]
Reminder: ask Eric to show you current v1.5 analytics stuff

**Comment by jimmykodes** [comment]
Fairly sure this was finished by Bailey
