### ISSUE TITLE
Deleting submissions

### ISSUE THREAD

**Issue by magrichard** [codalab/competitions-v2#633]
Dear @ckcollab,

In the frame of the COMETH project, sensitive clinical datasets will be submitted use the bot-submission mode from the METEOR web interface.
As COMETH competition admins, we are committed to deleting (completely) these datasets after a given amount of time of time.

I would like to now if there is an easy way :

[1] to do it manually? If I go in the admin>submissions menu of the competition and click on the delete submission button, will that definitely delete the submission in the codabench storage cloud?
![Capture d’écran 2021-01-13 à 10 44 38](https://user-images.githubusercontent.com/18577578/104435412-a65fa300-558c-11eb-98f9-18487e68cff9.png)

[2] to do it semi-automatically? For instance, erase all bot-submission, or all submissions from a particular user?

Thank you very mmuch

**Comment by Logan-Ruf** [comment]
[1] In response to your question, yes. When you delete a submission the corresponding data file is deleted from storage.

**Comment by Logan-Ruf** [comment]
With our contract end, we didn't have time to add a multi delete feature, but I did add the ability to sort the columns on the table of submissions. Hopefully, that will make things easier for you.

**Comment by magrichard** [comment]
Perfect. Thank you!

**Comment by Logan-Ruf** [comment]
You can now select multiple submissions in the submission manager and delete or re-run them all through one button. You can also filter and use the select all feature in combination to make selecting many submissions easy.

**Comment by twankim** [comment]
One relevant question. When we delete the competition from codalab website, will the corresponding data file (eval script, data, submission, etc.) deleted from the storage too?
