### ISSUE TITLE
Codabench queue configuration problem?

### ISSUE THREAD

**Issue by picaultj** [codalab/competitions-v2#677]
I’m currently trying to set up a benchmark using Codabench, but I’m facing some problems regarding queue configuration.
Please could you help w.r.t. the following problem?

My configuration is the following:
-	I created a bundle on codabench: https://www.codabench.org/competitions/380/?secret_key=12b3e5c8-26d1-4023-a46e-4ff8b0092627
-	I created a queue on codabench. The displayed broker URL is: pyamqp://55efc5fd-dce7-4f3f-8e77-ed6903355312:4686f918-8e96-4e1f-9e48-23496b826ee9@rabbit:5672/13aaff90-683b-4a0d-8c32-0a4d8fcb0bbe
-	I created a worker on a AWS server, and the .env file is the following:
BROKER_URL=pyamqp://55efc5fd-dce7-4f3f-8e77-ed6903355312:4686f918-8e96-4e1f-9e48-23496b826ee9@codalabcomp-v2-prod.lri.fr:5672/13aaff90-683b-4a0d-8c32-0a4d8fcb0bbe 
HOST_DIRECTORY=/home/ubuntu/codabench/storage 
#BROKER_USE_SSL=True

Note that I changed in the BROKER_URL “**rabbit**” to “**codalabcomp-v2-prod.lri.fr**” otherwise the worker was not able to start properly.

I observe the following behavior:
-	My worker seems to start correctly (“compute-worker@fe79c4a29b69 ready”)
-	When I upload a submission on the codabench web interface it seems to be received correctly by the worker (“Received task: compute_worker_run[838a4ea2-644f-4479-b2ca-d671be0db338]” + details of the arguments)
-	The worker does not seem to be able to send back the answer (“Updating submission @ https://codabench.org/api/submissions/3611/ with data = {'status': 'Preparing', 'status_details': None, 'secret': 'd0dbe97c-6def-420d-b1e3-272de9089494'}”), it generates the error:
Task compute_worker_run[838a4ea2-644f-4479-b2ca-d671be0db338] raised unexpected: **SSLError(MaxRetryError("HTTPSConnectionPool(host='codabench.org', port=443): Max retries exceeded with url: /api/submissions/3611/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))"))**
                and, therefore the status of the submission is not updated on the codabench web interface.

Do you have any idea about the source of the problem?
Please find attached the logs of the worker for more details.

Best regards,
Jérôme

NB. I tried also to use one of the available public queue of Codabench, but I did not manage to see any trace of execution of my benchmark.

[logs.txt](https://github.com/codalab/competitions-v2/files/7828357/logs.txt)

**Comment by NehzUx** [comment]
This issue has been resolved. The reason is the API url configuration error.  `www.` should be added.
