### ISSUE TITLE
Factories for testing

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#91]
Some way to generate:
- [x] 10 new users
- [ ] 10 new submissions
    * creating users if not provided
    * competition must be provided
    * optionally automatically execute submissions
    * optionally automatically attempt to add to leaderboard
- [ ] 10 new competitions 
    * must create phase/etc. required fields
    * optionally creating users
    * optionally creating submissions

Use [factory boy](https://github.com/FactoryBoy/factory_boy)

**Comment by jimmykodes** [comment]
- [ ] Create `generate_data` management command implementing these factories.
